### ISSUE TITLE
Avoid invoking NPM

### ISSUE THREAD

**Issue by SCjona** [WarningImHack3r/npm-update-dependencies#136]
### Issue type

performance improvement

### Description

The plugin runs `npm v package deprecated --registry=https://registry.npmjs.org` to check for package deprecation.

This can be replaced by a simple HTTP GET request to the registry `https://registry.npmjs.org/$package/$version` (`$version` can be `latest` or whatever you need to check).

`npm view` always performs that HTTP GET request for you, so it's better to do it directly (and possibly cache it #135). Also `npm` has a big CPU overhead as running just `npm help` takes 150ms on my system, `npm view` around 400ms

### Special case

- [X] This is not a bug nor a feature request, I can't use other templates

**Comment by WarningImHack3r** [comment]
After rereading the code, here's what I found:
- fetching the version online is always the first step, however, my logic was flawed because the fallback-to-npm-command part was called anyway when the `deprecated` key was not found, not _only_ when the fetch _actually_ failed (as it should've been)
- I spotted an improvement in my `deprecated: false` situation handling, so that's fixed too
- this is unfortunately the only place where a local `npm` command call can be avoided (and should've been in the first place): I still need it in many places
	- `npm config ls` to get all custom registries
	- `npm v <package> dist.tarball` to get the package's associated remote registry
	- `npm v <package> (version|versions|deprecated)` as a fallback to the fetched version, especially with custom registries/private packages
	- and more?

Anyway, that specific problem with `deprecated` is solved!

**Comment by SCjona** [comment]
`npm v <package> dist.tarball` => try `npm ls --json`, look at the resolved field. note: this only works if the packages are installed in node_modules, otherwise you'll get an error and/or partial response. this works without network connections and gets most of the data in one go. if a package is not resolved with that you will still have the fallback to the old command.

**Comment by WarningImHack3r** [comment]
Can't you stop having good ideas 😂 joke aside, I'll absolutely use that!!
