### ISSUE TITLE
Show updates for strict version dependencies

### ISSUE THREAD

**Issue by IvanSavoskin** [WarningImHack3r/npm-update-dependencies#148]
### What problem are you trying to solve?

In some projects, it is important to control the update of dependencies and do it manually. There are several reasons for this:

- More control over updates. When installing new dependencies, others will not update themselves;
- More project security. Sometimes new versions may contain critical vulnerabilities or backdoors;
- Not all library authors follow semantic versioning. Therefore, a minor update can cause a problem with the code, and with non-strict versioning, it will not always be obvious which library broke what (this has happened several times, for example with css-loader, after updating to a minor version of which the build broke).

At the same time, clicking through each dependency manually to understand whether it has a new version or not is very time-consuming and inconvenient

### Describe the solution you’d like

It would be great to return to the behavior that existed before 3.0.2, when an update was offered for all dependencies, including strictly versioned ones.

### Describe any alternatives you’ve also considered

- Manually click on each dependency and look for the latest version in the registry;
- Using IDEA tools, look for the latest version available for installation;
- Use version 3.0.2 until it is compatible with IntelliJ product updates

**Comment by WarningImHack3r** [comment]
I'm very balanced about this idea. Here's why.

### Pros
- It fits perfectly your use case of granular control
- I could show you the latest update, but no satisfying version as there is obviously none
- All packages don't follow SemVer, so you can't even use `~`
- Plugin annotations are optional
- `npm outdated` shows satisfying versions (as if they were using `^`) as well as latest, even for static comparators

### Cons
- **Additional computing time and annotations can be annoying for users who consider a static version as meaning "I don't want any update"**
  - `npm install <package>` installs with the `^` comparator by default, **static versions are often very intentional**
- It requires more computing and network calls when you may not want/need it, especially when the ratio of static comparator increases or when you have a bad connection
  - 3.1.0 and 3.2.0 have significantly improved performance, I'd like to keep their benefits and avoid bullying them by introducing computing-heavy changes

I also would like to avoid adding _yet another_ setting, I find it overwhelming, and sometimes good defaults are better than too many options (especially for such a small choice).

I know you'll be on the Pros' side, but I'd like to balance my features for _everyone_. I try to be as objective as possible and follow standards as much as possible.

All that said, what do you think? (poll open to as many people as possible of course)

**Comment by IvanSavoskin** [comment]
@WarningImHack3r 
I fully agree with any option you choose, since you are the creator of this plugin and the final decision is yours.

Of course, personally, it would be very useful for me to add the ability to receive information about existing updates. At the same time, I understand that many do not need this and would not like to lose performance due to unnecessary requests and checks (on the other hand, this should not be something unnecessary, because checks are performed only in a specific file - package.json).

I would say that additional settings would be the best option so that the user can enable or disable this behavior, but I agree with you that it is overwhelming in this case

**Comment by IvanSavoskin** [comment]
Since I don't know how many other users used this feature before version 3.1.0, I can't say whether someone needs it or not. Perhaps there are other users who needed it. Probably, if this is only my request and others are happy with the fix for this behavior in 3.1.0, then there is no need to improve anything.
But it would be interesting to know how many people used the plugin this way before

**Comment by WarningImHack3r** [comment]
I'd like to too! That said, a poll with a large number of users would represent the most popular answer, not necessarily the good one (if there is even a good answer to this - what `npm outdated` does looks like the wisest in that case)

**Comment by IvanSavoskin** [comment]
But, at the same time, version 3.0.2 works correctly in this case and does not show that express needs to be updated

**Comment by IvanSavoskin** [comment]
> What do you mean? You're on 4.x and it doesn't show the upgrade to 5? Sounds wrong to me

No, I mean I have version 5.0.1 and plugin doesn't offer me to update to 4.21.0 like `npm outdated` does. And this is precisely correct behavior.

**Comment by WarningImHack3r** [comment]
Indeed, even though if you downgrade to 5.0.0 it probably won't show you the 5.0.1 update!

**Comment by IvanSavoskin** [comment]
Yes, that's true. I checked it now and the update is not shown on version 5.0.0

**Comment by WarningImHack3r** [comment]
I noted that issue locally, but you can open another issue for that if you want.

In the meantime, I decided to create a setting for this issue: a checkbox to enable checking for updates on static comparators. It's **off by default**.

**Comment by IvanSavoskin** [comment]
This is great news! Thanks!

**Comment by WarningImHack3r** [comment]
Thanks for being open-minded and kind!

**Comment by WarningImHack3r** [comment]
Hi @IvanSavoskin, can you create an issue related to the Express latest version thing, please? I need to improve my overall support for tagged versions (beta, next, and stuff) while handling this latest version computation better as well.

**Comment by IvanSavoskin** [comment]
Hi @WarningImHack3r 
I made a new issue with this problem https://github.com/WarningImHack3r/npm-update-dependencies/issues/150

> (I just pressed "Release" for the newest version containing the feature for this issue by the way!)

This is just great news! Thank you very much! Especially for such incredible speed

**Comment by WarningImHack3r** [comment]
> Hi @WarningImHack3r I made a new issue with this problem

Wow, that was so fast, thanks!

> This is just great news! Thank you very much! Especially for such incredible speed

No worries haha, I love making my stuff better!

**Comment by WarningImHack3r** [comment]
> Version 3.4.0 is very cool! Thank you very much!

Glad you like it!!
