### ISSUE TITLE
progress bar showing the number of dependencies being checked

### ISSUE THREAD

**Issue by axel7083** [WarningImHack3r/npm-update-dependencies#59]
### What problem are you trying to solve?

Improving the `Scanning dependencies...` status bar text to include something with more details

### Describe the solution you’d like

A progress bar with a tooltip showing the number of elements remaining or the progress % or indicator "X/Y done"

**Comment by WarningImHack3r** [comment]
This would indeed be great! I initially did not do that because it would cause a lot of updates in the UI and also mainly because it takes a bunch of horizontal space in the status bar.
However, if I can find an appropriate and clear enough way to display it and that people do want it, then I could definitely consider this!

**Comment by WarningImHack3r** [comment]
Update: I drafted a quick implementation and I quite like it! Pushing 2.1.2 with a bunch of little tweaks :)

**Comment by axel7083** [comment]
That would be amazing! 

> I forked and gave it a try to add the progress bar, but I've never worked on a Inteliji plugin, so you went way faster than me !
