### ISSUE TITLE
Add availability read npm registry from .npmrc

### ISSUE THREAD

**Issue by krasnovmv** [WarningImHack3r/npm-update-dependencies#7]
### What problem are you trying to solve?

Hi, I searched for solutions how to easy update deps in package.json and your plugin is the nearest thing I have found
I want suggest a cool feature: read registry parameter from .npmrc from root directory and use it
Sounds easy, but I am bad in Kotlin, so I can only make this feature request

I also have found many similar issues in jetbrains tracker, but nobody knows when they resolve it

### Describe the solution you’d like

Read registry from .npmrc when a project is opening and use this url when program will read remote data about dependency updates

**Comment by WarningImHack3r** [comment]
I'm not particularly familiar with `.npmrc` and all its keys, but basically, do you want your custom registry URL to be used instead of the default one `https://registry.npmjs.org/`?

It seems possible, but fallbacks have to be considered. For that purpose, I consider simply using `npm v <package-name> dist.tarball`, parsing the root URL, (caching it,) and then passing it to the default process.

As every custom registry is supposed to follow the same API schema as `https://registry.npmjs.org`, then all the existing code should work without issue. It also wouldn't conflict with `pnpm` or `yarn` projects as `npm` is almost, _if not always_, installed on all the machines `pnpm` or `yarn` is, and this `npm view` command does not write in any file.

Would this solve your issue? Is this solution acceptable?

**Comment by krasnovmv** [comment]
Sounds great!
I check `npm v <package-name> dist.tarball` in my pnpm monorepo installation and it shows url with custom registry root url as expected

**Comment by WarningImHack3r** [comment]
Successfully implemented it. Can you confirm that `http(s)://<your-registry>/<package-name>` and `http(s)://<your-registry>/<package-name>/latest` are indeed working in your browser?

I'll wait a few days to:
- Get your answer on that
- See if I get some feedback about other potential bugs/features
- And wait for a fix of the plugin template to be released, then I'll push the update!

**Comment by WarningImHack3r** [comment]
(Waiting for the release pipeline to be fixed so I can push the update, but for now I can't)
